'use client';

import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'te';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Header & Navigation
    'nav.about': 'About Us',
    'nav.programmes': 'Programmes',
    'nav.impact': 'Impact',
    'nav.news': 'News',
    'nav.volunteer': 'Volunteer',
    'nav.contact': 'Contact Us',
    'nav.donate': 'Donate Now',
    
    // Footer
    'footer.description': 'A registered Indian charitable trust dedicated to transforming the lives of orphaned children, women, and marginalised communities through education, nutrition, and care since 2001.',
    'footer.quickLinks': 'Quick Links',
    'footer.programmes': 'Programmes',
    'footer.contact': 'Contact',
    'footer.copyright': '© {year} Vishwashanthi Shrushti Seva Trust. Reg. No. 768K IV/2024 | FCRA Registered',
    
    // Footer Links & Address
    'footer.link.about': 'About Us',
    'footer.link.governance': 'Governance',
    'footer.link.legal': 'Legal & Compliance',
    'footer.link.reports': 'Annual Reports',
    'footer.link.faq': 'FAQ',
    'footer.link.children': "Children's Home",
    'footer.link.education': 'Education Support',
    'footer.link.women': "Women's Development",
    'footer.link.hiv': 'HIV/AIDS Awareness',
    'footer.link.environment': 'Environment',
    'footer.link.privacy': 'Privacy Policy',
    'footer.link.accessibility': 'Accessibility',
    'footer.link.grievance': 'Grievance Redressal',
    'footer.link.sitemap': 'Sitemap',
    'footer.address.title': 'Contact',
    'footer.officeHours.title': 'Office Hours',
    'footer.officeHours.days': 'Monday – Saturday: 9:00 AM – 6:00 PM IST',
    'footer.officeHours.sunday': 'Sunday: Closed',
    'footer.emergency.title': 'Emergency / Admissions',
    'footer.emergency.desc': 'For urgent child admission inquiries, please call us directly at',

    // Home Page
    'home.hero.badge': 'Registered Charitable Trust — Since 2001',
    'home.hero.title': 'Every child deserves',
    'home.hero.titleAccent': 'a home.',
    'home.hero.description': 'Vishwashanthi Shrushti Seva Trust provides shelter, education, nutrition, and holistic development for orphaned and semi-orphaned children in Telangana, India. Join us in transforming lives.',
    'home.hero.ctaDonate': 'Donate Now',
    'home.hero.ctaWork': 'Our Work',
    'home.hero.years': 'Years of impact',
    'home.programmes.title': 'Our Programmes',
    'home.programmes.subtitle': 'We run comprehensive programmes focused on shelter, education, health, and community empowerment.',
    
    'home.programmes.children.title': "Children's Home",
    'home.programmes.children.desc': 'Safe residential care, structured routines, and a loving environment for orphaned and semi-orphaned children aged 4–12.',
    'home.programmes.education.title': 'Education Support',
    'home.programmes.education.desc': 'School enrolment, uniforms, stationery, tuition, and computer literacy to build brighter futures.',
    'home.programmes.women.title': "Women's Development",
    'home.programmes.women.desc': 'Self-Help Groups, skill training, and economic empowerment for women in underserved communities.',
    'home.programmes.learnMore': 'Learn More',
    'home.trust.taxExempt': 'Tax Exempt',
    'home.trust.registeredNgo': 'Registered NGO',
    'home.trust.foreignDonations': 'Foreign Donations',
    'home.trust.securePayments': 'Secure Payments',

    'home.help.title': 'How You Can Help',
    'home.help.subtitle': 'Make a Difference',
    'home.help.donate.title': 'Donate',
    'home.help.donate.desc': 'Your contribution directly funds shelter, meals, and education for our children.',
    'home.help.donate.cta': 'Give Now',
    'home.help.volunteer.title': 'Volunteer',
    'home.help.volunteer.desc': 'Share your time, mentorship, and skills with children who need guidance.',
    'home.help.volunteer.cta': 'Join Us',
    'home.help.share.title': 'Spread the Word',
    'home.help.share.desc': 'Follow us, share our stories, and help us reach more supporters.',
    'home.help.share.cta': 'Connect',
    'home.banner.title': "Sponsor a child's complete care for",
    'home.banner.amount': '₹2,200 / month',
    'home.banner.desc': '100% of your donation goes directly to shelter, education, nutrition, and healthcare. Tax-deductible under Section 80G.',
    'home.banner.cta': 'Donate Now →',
    
    // Impact counter labels
    'impact.stats.children': 'Children in Care',
    'impact.stats.years': 'Years of Service',
    'impact.stats.meals': 'Meals Served',
    'impact.stats.students': 'Students Educated',

    // Donate Page
    'donate.hero.title': 'Your Gift',
    'donate.hero.titleAccent': 'Changes Lives',
    'donate.hero.desc': 'Every rupee you contribute goes directly towards shelter, education, and nutrition for children in our care. All donations are tax-deductible under Section 80G.',
    'donate.step1': '1. Choose Donation Tier',
    'donate.step2': '2. Donor Information',
    'donate.form.name': 'Full Name',
    'donate.form.namePlaceholder': 'Full name as on PAN card',
    'donate.form.email': 'Email Address',
    'donate.form.phone': 'Phone Number',
    'donate.form.country': 'Country',
    'donate.form.pan': 'PAN Card Number',
    'donate.form.panHelp': 'Income Tax Rules require PAN submission to issue a valid 80G tax exemption receipt. This data principal record is stored using AES-256 GCM encryption at rest.',
    'donate.form.address': 'Residential Address',
    'donate.form.consent': 'I consent to Vishwashanthi Shrushti Seva Trust storing and processing this personal data to initiate payment and generate tax exemption certificates under the India DPDP Act 2023.',
    'donate.form.submit': 'Proceed to Pay securely',
    'donate.form.processing': 'Processing secure checkout...',
    'donate.sidebar.title': 'Why Sponsor a Child?',
    'donate.sidebar.secure': 'Guaranteed Secure Checkout',

    'donate.frequency.one_time': 'Give Once',
    'donate.frequency.monthly': 'Monthly',
    'donate.frequency.yearly': 'Yearly',
    'donate.tier.shelter.name': 'Shelter',
    'donate.tier.shelter.desc': 'Provide safe housing and residential care for a child',
    'donate.tier.education.name': 'Education',
    'donate.tier.education.desc': "Fund a child's complete education including materials",
    'donate.tier.food.name': 'Food & Nutrition',
    'donate.tier.food.desc': 'Ensure balanced daily meals and health check-ups',
    'donate.tier.childcare.name': 'Full Child Care',
    'donate.tier.childcare.desc': "Sponsor a child's complete residential care and development",
    'donate.tier.custom.name': 'Custom Amount',
    'donate.tier.custom.desc': 'Specify any custom amount (min ₹100)',
    'donate.form.placeholder.name': 'Full name as on PAN card',
    'donate.form.placeholder.email': 'you@example.com',
    'donate.form.placeholder.phone': '+91 98765 43210',
    'donate.form.placeholder.amount': 'Enter amount',
    'donate.form.placeholder.address': 'Your billing / tax registration address',
    'donate.form.fcra': 'FCRA Compliance Routing',
    'donate.form.fcraDesc': 'Your donation will be securely routed in foreign currency directly to our State Bank of India main FCRA account, in complete compliance with Ministry of Home Affairs guidelines. Tax deduction receipt will be issued as a general foreign receipt.',
    'donate.form.validation.amount': 'Minimum donation amount is ₹100',
    'donate.form.validation.consent': 'You must provide consent for data processing under DPDP Act.',
    'donate.form.validation.pan': 'Please enter a valid PAN format (e.g. ABCDE1234F) for tax exemption.',
    'donate.form.submitPay': 'Proceed to Pay {amount} securely',
    'donate.success.title': 'Thank You For Your Support!',
    'donate.success.desc': 'We have received your contribution of {amount}. Your generosity directly powers the care and education of child beneficiaries.',
    'donate.success.receiptTitle': 'Donation Receipt Details',
    'donate.success.receiptNo': 'Receipt Number:',
    'donate.success.exemption': 'Exemption Type:',
    'donate.success.exemptionVal': 'Section 80G Tax Deductible',
    'donate.success.name': 'Donor Name:',
    'donate.success.pan': 'PAN Registered:',
    'donate.success.download': 'Download 80G Receipt',
    'donate.success.again': 'Donate Again',
    'donate.sidebar.feature.shelter': 'Safe sleeping quarters, 24/7 supervision, clean living environment',
    'donate.sidebar.feature.education': 'School enrolment fees, uniforms & stationery, computer literacy classes',
    'donate.sidebar.feature.food': '3 balanced meals daily, nutritional supplements, local medical care',
    'donate.sidebar.feature.childcare': 'All shelter & meals, complete education, health, music & extracurriculars',
    'donate.sidebar.benefit.1.title': 'Direct Care',
    'donate.sidebar.benefit.1.desc': 'Your sponsorship funds high-quality, continuous residential care including food, clothing, and safe lodging.',
    'donate.sidebar.benefit.2.title': 'High-Impact Education',
    'donate.sidebar.benefit.2.desc': 'We place children in english-medium private schools and fund professional tuition alongside digital literacy courses.',
    'donate.sidebar.benefit.3.title': 'Complete Accountability',
    'donate.sidebar.benefit.3.desc': 'Get transparent audited accounts and direct compliance updates on how funds are spent.',
    
    // About Page
    'about.hero.badge': 'About Vishwashanthi Shrushti Seva Trust',
    'about.hero.title': 'Transforming lives through',
    'about.hero.titleAccent': 'care and education',
    'about.hero.description': 'Vishwashanthi Shrushti Seva Trust is a registered Indian charitable trust (Reg. No. 768K IV/2024 / REGD.NO: 2091/2001) operating in Telangana. Since 2001, we have been committed to providing holistic care for orphaned and semi-orphaned children, empowering women through Self-Help Groups, and building healthier communities through awareness programmes.',
    'about.mission': 'Our Mission',
    'about.mission.desc': 'To provide a safe, nurturing home where every child receives quality education, balanced nutrition, healthcare, and the discipline to thrive — regardless of their circumstances. We empower women, support communities impacted by HIV/AIDS, and foster environmental stewardship.',
    'about.vision': 'Our Vision',
    'about.vision.desc': 'A society where no child is denied opportunity because of poverty, and where marginalised communities — women, the elderly, and those affected by disease — are empowered with the resources, skills, and dignity to lead fulfilling lives.',
    'about.values.title': 'Our Core Values',
    'about.journey.title': 'Our Journey',
    'about.cta.title': 'Join us in making a difference',
    'about.cta.desc': 'Your support transforms lives. Whether you donate, volunteer, or share our mission — every action counts.',

    'about.milestones.2001': 'Trust founded and registered under the Indian Trust Act',
    'about.milestones.2004': "Children's residential home established at Nagole",
    'about.milestones.2008': "Women's Self-Help Group programme launched",
    'about.milestones.2012': 'HIV/AIDS awareness campaign reaches 5,000+ individuals',
    'about.milestones.2016': 'Education Support programme expands to cover 200+ students',
    'about.milestones.2020': 'Emergency food distribution during COVID-19 pandemic',
    'about.milestones.2024': 'Re-registered under Govt. of Telangana (768K IV/2024)',

    'about.values.compassion.title': 'Compassion',
    'about.values.compassion.desc': 'We treat every child, woman, and elder with dignity, respect, and unconditional love.',
    'about.values.transparency.title': 'Transparency',
    'about.values.transparency.desc': 'Every rupee is accounted for. Audited reports are published annually and available for download.',
    'about.values.community.title': 'Community',
    'about.values.community.desc': 'We believe sustainable change comes from empowering communities, not creating dependency.',
    'about.values.accountability.title': 'Accountability',
    'about.values.accountability.desc': 'Registered and compliant with all Indian regulatory bodies — 80G, 12A, FCRA, and DPDP Act.',
    
    // Volunteer Page
    'volunteer.hero.badge': 'Get Involved',
    'volunteer.hero.title': 'Volunteer with',
    'volunteer.hero.description': "Share your time, skills, and compassion with children and communities who need it most. Whether you can spare a few hours a week or want to lead a project, there's a place for you.",
    'volunteer.roles.title': 'Volunteer Roles',

    'volunteer.role.teaching.title': 'Teaching & Tutoring',
    'volunteer.role.teaching.desc': 'Help children with homework, computer skills, and English language proficiency.',
    'volunteer.role.teaching.commitment': '4–6 hrs/week',
    'volunteer.role.mentorship.title': 'Mentorship',
    'volunteer.role.mentorship.desc': 'Provide guidance, career counselling, and emotional support to adolescents.',
    'volunteer.role.mentorship.commitment': '2–4 hrs/week',
    'volunteer.role.events.title': 'Event Coordination',
    'volunteer.role.events.desc': 'Organise fundraisers, awareness drives, and community engagement events.',
    'volunteer.role.events.commitment': 'Flexible',
    'volunteer.role.medical.title': 'Medical & Health',
    'volunteer.role.medical.desc': 'Conduct health camps, nutrition workshops, or provide medical expertise.',
    'volunteer.role.medical.commitment': 'Project-based',
    'volunteer.form.title': 'Volunteer Registration Form',
    'volunteer.form.name': 'Full Name',
    'volunteer.form.email': 'Email Address',
    'volunteer.form.phone': 'Phone',
    'volunteer.form.city': 'City / Town',
    'volunteer.form.skills': 'Skills & Areas of Interest',
    'volunteer.form.days': 'Available Days',
    'volunteer.form.hours': 'Weekly Commitment (Hours)',
    'volunteer.form.consent': 'I consent to Vishwashanthi Shrushti Seva Trust storing and processing this volunteer inquiry under the guidelines of India DPDP Act 2023.',
    'volunteer.form.submit': 'Submit Registration',
    'volunteer.form.submitting': 'Submitting Registration...',
    'volunteer.form.success.title': 'Registration Successful!',
    'volunteer.form.success.desc': 'Your registration has been submitted successfully! Our volunteer coordinator will reach out to you soon.',
    'volunteer.form.success.button': 'Register another volunteer',
    'volunteer.form.validation.name': 'Name must be at least 2 characters.',
    'volunteer.form.validation.city': 'City must be at least 2 characters.',
    'volunteer.form.validation.skills': 'Please select at least one skill/area of interest.',
    'volunteer.form.validation.days': 'Please select at least one day of availability.',
    'volunteer.form.validation.hours': 'Minimum 1 hour per week commitment is required.',
    'volunteer.form.validation.consent': 'You must consent to data processing under DPDP guidelines.',
    'volunteer.form.validation.phone': 'Invalid phone number format (e.g. +919876543210).',
    'volunteer.form.placeholder.name': 'Your name',
    'volunteer.form.placeholder.city': 'E.g. Hyderabad',
    'volunteer.skill.teaching': 'Teaching & Tutoring',
    'volunteer.skill.mentorship': 'Mentorship',
    'volunteer.skill.events': 'Event Coordination',
    'volunteer.skill.medical': 'Medical & Health Support',
    'volunteer.skill.content': 'Content Writing & Social Media',
    'volunteer.skill.it': 'IT & Graphic Design',
    'volunteer.skill.admin': 'Administrative Support',
    
    // Contact Page
    'contact.hero.badge': 'Get in Touch',
    'contact.hero.title': 'Contact Us',
    'contact.hero.description': "We'd love to hear from you. Whether you have questions about our programmes, want to donate, volunteer, or enquire about child admissions — reach out and we'll respond within 24 hours.",
    'contact.form.name': 'Full Name',
    'contact.form.email': 'Email',
    'contact.form.phone': 'Phone',
    'contact.form.subject': 'Subject',
    'contact.form.message': 'Message',
    'contact.form.consent': 'I consent to Vishwashanthi Shrushti Seva Trust processing my personal data as described in the Privacy Policy.',
    'contact.form.submit': 'Send Message',
    'contact.sidebar.title': 'Reach Us Directly',

    'contact.sidebar.address': 'H.No. 2-6-410, Jaipuri Colony, Nagole, Uppal Mandal, Medchal Malkajgiri District, Telangana, India',
    'contact.sidebar.hours.title': 'Office Hours',
    'contact.sidebar.hours.days': 'Monday – Saturday: 9:00 AM – 6:00 PM IST',
    'contact.sidebar.hours.sunday': 'Sunday: Closed',
    'contact.sidebar.emergency.title': 'Emergency / Admissions',
    'contact.sidebar.emergency.desc': 'For urgent child admission inquiries, please call us directly at',
    'contact.form.subject.general': 'General Inquiry',
    'contact.form.subject.admission': 'Child Admission Enquiry',
    'contact.form.subject.partnership': 'Partnership / CSR',
    'contact.form.subject.media': 'Media & Press',
    'contact.form.validation.name': 'Name must be at least 2 characters.',
    'contact.form.validation.message': 'Message must be at least 10 characters.',
    'contact.form.validation.consent': 'You must consent to data processing under DPDP guidelines.',
    'contact.form.validation.phone': 'Invalid phone number format (e.g. +919876543210).',
    'contact.form.success': 'Your message has been sent successfully. We will get back to you within 24 hours!',
    'contact.form.success.title': 'Inquiry Sent!',
    'contact.form.success.button': 'Send another inquiry',
    'contact.form.placeholder.name': 'Your full name',
    'contact.form.placeholder.email': 'you@example.com',
    'contact.form.placeholder.phone': '+91 98765 43210',
    'contact.form.placeholder.message': 'Tell us how we can help you...',
    'contact.form.sending': 'Sending Message...',

    // Programmes Page
    'programmes.hero.badge': 'Our Work',
    'programmes.hero.title': 'Programmes that',
    'programmes.hero.titleAccent': 'transform communities',
    'programmes.hero.desc': "From residential childcare to women's empowerment, our programmes address the most critical needs of marginalised populations across Telangana.",
    'programmes.card.children.title': "Children's Home",
    'programmes.card.children.desc': 'Safe residential care with structured routines, discipline, and a loving family environment for orphaned and semi-orphaned children aged 4–12.',
    'programmes.card.children.stats': '120+ children in care',
    'programmes.card.education.title': 'Education Support',
    'programmes.card.education.desc': 'Complete educational assistance including school enrolment, uniforms, stationery, tuition, and computer literacy for underserved children.',
    'programmes.card.education.stats': '500+ students supported',
    'programmes.card.women.title': "Women's Development",
    'programmes.card.women.desc': "Empowering women through Self-Help Groups (SHGs), skill training, microfinance access, and community leadership development.",
    'programmes.card.women.stats': '15+ active SHGs',
    'programmes.card.hiv.title': 'HIV/AIDS Awareness',
    'programmes.card.hiv.desc': 'Community-level awareness campaigns, testing facilitation, de-stigmatisation drives, and support for affected individuals and families.',
    'programmes.card.hiv.stats': '5,000+ lives reached',
    'programmes.card.environment.title': 'Environment',
    'programmes.card.environment.desc': 'Tree plantation drives, clean-up campaigns, and awareness programmes promoting environmental sustainability in local communities.',
    'programmes.card.environment.stats': 'Ongoing initiatives',
    'programmes.card.aged.title': 'Care for the Aged',
    'programmes.card.aged.desc': 'Planned residential homes for elderly men and women without family support, ensuring dignity, medical care, and companionship.',
    'programmes.card.aged.stats': 'Coming Soon',
    
    // Days
    'day.mon': 'Mon',
    'day.tue': 'Tue',
    'day.wed': 'Wed',
    'day.thu': 'Thu',
    'day.fri': 'Fri',
    'day.sat': 'Sat',
    'day.sun': 'Sun',

    // Countries
    'country.IN': 'India',
    'country.US': 'United States',
    'country.GB': 'United Kingdom',
    'country.CA': 'Canada',
    'country.AU': 'Australia',
    'country.SG': 'Singapore',
    'country.DE': 'Germany',
    'country.FR': 'France',
    'country.AE': 'United Arab Emirates',

    // Donate Page FAQs & Pricing Frequencies
    'donate.frequency.once.abbr': 'once',
    'donate.frequency.monthly.abbr': 'mo',
    'donate.frequency.yearly.abbr': 'yr',
    'donate.trust.exempt': 'Tax Exempt Certified',
    'donate.trust.secure': '256-bit Secure',
    'donate.trust.funds': 'Funds to Programmes',
    'donate.faq.title': 'Common Questions About Donating',
    'donate.faq.more': 'Have more questions? Contact us or call +91 80745 89091',
    'donate.faq.or': 'or',
    'donate.faq.contactUs': 'Contact us',
    'donate.faq.q1': 'Is my donation tax-deductible?',
    'donate.faq.a1': 'Yes. Vishwashanthi Shrushti Seva Trust is registered under Section 80G of the Income Tax Act. You will receive a valid 80G receipt for every donation, which can be used to claim tax deductions.',
    'donate.faq.q2': 'Can I donate from outside India?',
    'donate.faq.a2': 'Yes. We are FCRA registered and can accept donations in foreign currency. Foreign donations are processed through our designated FCRA bank account in compliance with Indian law.',
    'donate.faq.q3': 'How is my money used?',
    'donate.faq.a3': '100% of your donation goes directly to programme expenses — shelter, food, education, and healthcare for children. Administrative costs are funded separately through institutional grants.',
    'donate.faq.q4': 'Will I get updates on the child I sponsor?',
    'donate.faq.a4': 'Monthly sponsors receive quarterly progress updates including academic performance and well-being reports. We respect children\'s privacy and follow strict consent guidelines for any photographs shared.',
    'donate.faq.q5': 'Can I cancel my recurring donation?',
    'donate.faq.a5': 'Yes, you can cancel or modify your recurring donation at any time through your donor dashboard or by contacting us directly at +91 80745 89091.',
    'programmes.card.learnMore': 'Learn More',
  },
  te: {
    // Header & Navigation
    'nav.about': 'మా గురించి',
    'nav.programmes': 'కార్యక్రమాలు',
    'nav.impact': 'ప్రభావం',
    'nav.news': 'వార్తలు',
    'nav.volunteer': 'స్వచ్ఛంద సేవ',
    'nav.contact': 'మమ్మల్ని సంప్రదించండి',
    'nav.donate': 'విరాళం ఇవ్వండి',
    
    // Footer
    'footer.description': '2001 నుండి విద్య, పోషకాహారం మరియు సంరక్షణ ద్వారా అనాథ పిల్లలు, మహిళలు మరియు వెనుకబడిన వర్గాల జీవితాలను మార్చడానికి అంకితమైన నమోదిత భారతీయ స్వచ్ఛంద సంస్థ.',
    'footer.quickLinks': 'త్వరిత లింకులు',
    'footer.programmes': 'కార్యక్రమాలు',
    'footer.contact': 'సంప్రదించండి',
    'footer.copyright': '© {year} విశ్వశాంతి సృష్టి సేవ ట్రస్ట్. రిజిస్టర్ నెం. 768K IV/2024 | FCRA నమోదిత సంస్థ',
    
    // Footer Links & Address
    'footer.link.about': 'మా గురించి',
    'footer.link.governance': 'పాలన',
    'footer.link.legal': 'చట్టపరమైన & వర్తింపు',
    'footer.link.reports': 'వార్షిక నివేదికలు',
    'footer.link.faq': 'తరచుగా అడిగే ప్రశ్నలు',
    'footer.link.children': 'పిల్లల హోమ్',
    'footer.link.education': 'విద్యా సహాయం',
    'footer.link.women': 'మహిళా సాధికారత',
    'footer.link.hiv': 'HIV/AIDS అవగాహన',
    'footer.link.environment': 'పర్యావరణం',
    'footer.link.privacy': 'గోప్యతా విధానం',
    'footer.link.accessibility': 'యాక్సెసిబిలిటీ',
    'footer.link.grievance': 'ఫిర్యాదుల పరిష్కారం',
    'footer.link.sitemap': 'సైట్‌మ్యాప్',
    'footer.address.title': 'సంప్రదించండి',
    'footer.officeHours.title': 'కార్యాలయ వేళలు',
    'footer.officeHours.days': 'సోమవారం - శనివారం: ఉదయం 9:00 - సాయంత్రం 6:00 IST',
    'footer.officeHours.sunday': 'ఆదివారం: సెలవు',
    'footer.emergency.title': 'అత్యవసర పరిస్థితి / ప్రవేశాలు',
    'footer.emergency.desc': 'అత్యవసర పిల్లల ప్రవేశాల విచారణ కోసం, దయచేసి నేరుగా మమ్మల్ని సంప్రదించండి',

    // Home Page
    'home.hero.badge': 'నమోదిత స్వచ్ఛంద ట్రస్ట్ — 2001 నుండి',
    'home.hero.title': 'ప్రతి బిడ్డకు అవసరం',
    'home.hero.titleAccent': 'ఒక ఇల్లు.',
    'home.hero.description': 'విశ్వశాంతి సృష్టి సేవ ట్రస్ట్ తెలంగాణలో అనాథ మరియు నిరుపేద పిల్లల సంరక్షణ, విద్య, పోషణ మరియు సంపూర్ణ అభివృద్ధిని అందిస్తుంది. జీవితాలను మార్చడంలో మాతో చేరండి.',
    'home.hero.ctaDonate': 'విరాళం ఇవ్వండి',
    'home.hero.ctaWork': 'మా సేవలు',
    'home.hero.years': 'సంవత్సరాల సేవ',
    'home.programmes.title': 'మా కార్యక్రమాలు',
    'home.programmes.subtitle': 'మేము పిల్లల సంరక్షణ, విద్య, ఆరోగ్యం మరియు మహిళా సాధికారతపై సమగ్ర కార్యక్రమాలను నిర్వహిస్తున్నాము.',
    
    'home.programmes.children.title': 'పిల్లల హోమ్',
    'home.programmes.children.desc': '4-12 సంవత్సరాల వయస్సు గల అనాథ మరియు నిరుపేద పిల్లలకు సురక్షితమైన నివాస సంరక్షణ, నిర్మాణాత్మక దినచర్యలు మరియు ప్రేమపూర్వక వాతావరణం.',
    'home.programmes.education.title': 'విద్యా సహాయం',
    'home.programmes.education.desc': 'ఉజ్వల భవిష్యత్తును నిర్మించడానికి పాఠశాల నమోదు, యూనిఫాంలు, స్టేషనరీ, ట్యూషన్ మరియు కంప్యూటర్ పరిజ్ఞానం.',
    'home.programmes.women.title': 'మహిళా సాధికారత',
    'home.programmes.women.desc': 'వెనుకబడిన వర్గాల మహిళల కోసం స్వయం సహాయక బృందాలు, నైపుణ్య శిక్షణ మరియు ఆర్థిక సాధికారత.',
    'home.programmes.learnMore': 'మరింత తెలుసుకోండి',
    'home.trust.taxExempt': 'పన్ను మినహాయింపు',
    'home.trust.registeredNgo': 'నమోదిత స్వచ్ఛంద సంస్థ',
    'home.trust.foreignDonations': 'విదేశీ విరాళాలు',
    'home.trust.securePayments': 'సురక్షిత చెల్లింపులు',

    'home.help.title': 'మీరు ఎలా సహాయపడగలరు',
    'home.help.subtitle': 'సహాయం చేయండి',
    'home.help.donate.title': 'విరాళం ఇవ్వండి',
    'home.help.donate.desc': 'మీ విరాళం నేరుగా మా పిల్లల సంరక్షణ, భోజనం మరియు విద్యకు ఉపయోగపడుతుంది.',
    'home.help.donate.cta': 'ఇప్పుడే ఇవ్వండి',
    'home.help.volunteer.title': 'స్వచ్ఛంద సేవ',
    'home.help.volunteer.desc': 'మార్గదర్శకత్వం అవసరమైన పిల్లలతో మీ సమయం, నైపుణ్యాలను పంచుకోండి.',
    'home.help.volunteer.cta': 'మాతో చేరండి',
    'home.help.share.title': 'ప్రచారం చేయండి',
    'home.help.share.desc': 'మమ్మల్ని అనుసరించండి, మా కథనాలను పంచుకోండి మరియు మరింత మందిని చేరడానికి సహాయపడండి.',
    'home.help.share.cta': 'కనెక్ట్ అవ్వండి',
    'home.banner.title': 'ఒక బిడ్డ సంపూర్ణ సంరక్షణను స్పాన్సర్ చేయండి',
    'home.banner.amount': 'నెలకు ₹2,200',
    'home.banner.desc': 'మీ విరాళంలో 100% నేరుగా నివాసం, విద్య, పోషకాహారం మరియు ఆరోగ్య సంరక్షణకు వెళుతుంది. సెక్షన్ 80G కింద పన్ను మినహాయింపు ఉంది.',
    'home.banner.cta': 'ఇప్పుడే విరాళం ఇవ్వండి →',
    
    // Impact counter labels
    'impact.stats.children': 'సంరక్షణలో ఉన్న పిల్లలు',
    'impact.stats.years': 'సంవత్సరాల సేవ',
    'impact.stats.meals': 'భోజనాలు అందించబడ్డాయి',
    'impact.stats.students': 'చదువుకున్న విద్యార్థులు',

    // Donate Page
    'donate.hero.title': 'మీ సహాయం',
    'donate.hero.titleAccent': 'జీవితాలను మారుస్తుంది',
    'donate.hero.desc': 'మీరు అందించే ప్రతి రూపాయి మా సంరక్షణలోని పిల్లల ఆశ్రయం, విద్య మరియు పోషణకు ఉపయోగపడుతుంది. అన్ని విరాళాలు సెక్షన్ 80G కింద పన్ను మినహాయింపు పొందుతాయి.',
    'donate.step1': '1. విరాళం స్థాయిని ఎంచుకోండి',
    'donate.step2': '2. దాతల సమాచారం',
    'donate.form.name': 'పూర్తి పేరు',
    'donate.form.namePlaceholder': 'పాన్ కార్డ్ లో ఉన్న విధంగా పూర్తి పేరు',
    'donate.form.email': 'ఈమెయిల్ చిరునామా',
    'donate.form.phone': 'ఫోన్ నంబర్',
    'donate.form.country': 'దేశం',
    'donate.form.pan': 'పాన్ కార్డ్ నంబర్',
    'donate.form.panHelp': '80G పన్ను మినహాయింపు రసీదు జారీ చేయడానికి ఆదాయపు పన్ను నిబంధనల ప్రకారం పాన్ సమర్పించడం తప్పనిసరి. ఈ డేటా ఎన్క్రిప్ట్ చేయబడి భద్రపరచబడుతుంది.',
    'donate.form.address': 'నివాస చిరునామా',
    'donate.form.consent': 'భారతదేశ DPDP చట్టం 2023 కింద పేమెంట్ ప్రారంభించడానికి మరియు పన్ను మినహాయింపు సర్టిఫికెట్లను జారీ చేయడానికి ఈ వ్యక్తిగత డేటాను నిల్వ చేయడానికి మరియు ప్రాసెస్ చేయడానికి నేను విశ్వశాంతి సృష్టి సేవ ట్రస్ట్ కు సమ్మతిస్తున్నాను.',
    'donate.form.submit': 'సురక్షితంగా పేమెంట్ చేయండి',
    'donate.form.processing': 'సురక్షితమైన చెల్లింపు ప్రక్రియ జరుగుతోంది...',
    'donate.sidebar.title': 'పిల్లాడిని ఎందుకు స్పాన్సర్ చేయాలి?',
    'donate.sidebar.secure': 'సురక్షితమైన చెల్లింపుల హామీ',

    'donate.frequency.one_time': 'ఒక్కసారి ఇచ్చుట',
    'donate.frequency.monthly': 'నెలవారీ',
    'donate.frequency.yearly': 'సంవత్సరానికి',
    'donate.tier.shelter.name': 'ఆశ్రయం',
    'donate.tier.shelter.desc': 'ఒక బిడ్డకు సురక్షితమైన నివాసం మరియు సంరక్షణను అందించండి',
    'donate.tier.education.name': 'విద్య',
    'donate.tier.education.desc': 'విద్యా సామాగ్రితో సహా పిల్లల పూర్తి విద్యా ఖర్చులను భరించండి',
    'donate.tier.food.name': 'భోజనం & పోషకాహారం',
    'donate.tier.food.desc': 'ప్రతిరోజూ సమతుల్య భోజనం మరియు ఆరోగ్య తనిఖీలను నిర్ధారించండి',
    'donate.tier.childcare.name': 'పూర్తి బాలల సంరక్షణ',
    'donate.tier.childcare.desc': 'ఒక బిడ్డ పూర్తి నివాస సంరక్షణ మరియు అభివృద్ధిని స్పాన్సర్ చేయండి',
    'donate.tier.custom.name': 'ఇతర మొత్తం',
    'donate.tier.custom.desc': 'ఏదైనా ఇతర మొత్తాన్ని పేర్కొనండి (కనీసం ₹100)',
    'donate.form.placeholder.name': 'పాన్ కార్డ్ లో ఉన్న విధంగా పూర్తి పేరు',
    'donate.form.placeholder.email': 'you@example.com',
    'donate.form.placeholder.phone': '+91 98765 43210',
    'donate.form.placeholder.amount': 'మొత్తాన్ని నమోదు చేయండి',
    'donate.form.placeholder.address': 'మీ బిల్లింగ్ / పన్ను నమోదు చిరునామా',
    'donate.form.fcra': 'FCRA వర్తింపు రూటింగ్',
    'donate.form.fcraDesc': 'మీ విరాళం విదేశీ కరెన్సీలో మా స్టేట్ బ్యాంక్ ఆఫ్ ఇండియా ప్రధాన FCRA ఖాతాకు సురక్షితంగా పంపబడుతుంది, ఇది కేంద్ర హోం వ్యవహారాల మంత్రిత్వ శాఖ నిబంధనలకు అనుగుణంగా ఉంటుంది. విరాళం రసీదు జారీ చేయబడుతుంది.',
    'donate.form.validation.amount': 'కనీస విరాళం మొత్తం ₹100',
    'donate.form.validation.consent': 'DPDP చట్టం కింద డేటా ప్రాసెసింగ్ కోసం మీరు సమ్మతిని అందించాలి.',
    'donate.form.validation.pan': 'పన్ను మినహాయింపు కోసం దయచేసి సరైన పాన్ నంబర్ నమోదు చేయండి (ఉదా. ABCDE1234F).',
    'donate.form.submitPay': 'సురక్షితంగా {amount} చెల్లించండి',
    'donate.success.title': 'మీ మద్దతుకు ధన్యవాదాలు!',
    'donate.success.desc': 'మేము మీ నుండి {amount} విరాళం స్వీకరించాము. మీ ఉదారత నేరుగా పిల్లల సంరక్షణ మరియు విద్యకు సహాయపడుతుంది.',
    'donate.success.receiptTitle': 'విరాళం రసీదు వివరాలు',
    'donate.success.receiptNo': 'రసీదు సంఖ్య:',
    'donate.success.exemption': 'మినహాయింపు రకం:',
    'donate.success.exemptionVal': 'సెక్షన్ 80G పన్ను మినహాయింపు',
    'donate.success.name': 'దాత పేరు:',
    'donate.success.pan': 'నమోదిత పాన్:',
    'donate.success.download': '80G రసీదును డౌన్‌లోడ్ చేయండి',
    'donate.success.again': 'మరోసారి విరాళం ఇవ్వండి',
    'donate.sidebar.feature.shelter': 'సురక్షితమైన పడక గదులు, 24/7 పర్యవేక్షణ, శుభ్రమైన జీవన వాతావరణం',
    'donate.sidebar.feature.education': 'పాఠశాల ప్రవేశ రుసుములు, యూనిఫాంలు & స్టేషనరీ, కంప్యూటర్ తరగతులు',
    'donate.sidebar.feature.food': 'రోజుకు 3 సమతుల్య భోజనాలు, పోషకాహార సప్లిమెంట్లు, స్థానిక వైద్య సంరక్షణ',
    'donate.sidebar.feature.childcare': 'అన్ని ఆశ్రయం & భోజనాలు, పూర్తి విద్య, ఆరోగ్యం, సంగీతం & ఇతర కార్యక్రమాలు',
    'donate.sidebar.benefit.1.title': 'నేరుగా సంరక్షణ',
    'donate.sidebar.benefit.1.desc': 'మీ స్పాన్సర్‌షిప్ నిధులు నివాస సంరక్షణకు, ఆహారం, బట్టలు మరియు సురక్షితమైన ఆశ్రయం కోసం ఉపయోగించబడతాయి.',
    'donate.sidebar.benefit.2.title': 'నాణ్యమైన విద్య',
    'donate.sidebar.benefit.2.desc': 'మేము పిల్లలను ఇంగ్లీష్ మీడియం ప్రైవేట్ పాఠశాలల్లో చేర్చి, కంప్యూటర్ పరిజ్ఞానంతో పాటుగా నాణ్యమైన విద్యను అందిస్తాము.',
    'donate.sidebar.benefit.3.title': 'పూర్తి పారదర్శకత',
    'donate.sidebar.benefit.3.desc': 'నిధులు ఎలా ఖర్చు చేయబడుతున్నాయో తెలుసుకోవడానికి పారదర్శక ఆడిట్ ఖాతాలు మరియు నియంత్రణ నవీకరణలను పొందండి.',
    
    // About Page
    'about.hero.badge': 'విశ్వశాంతి సృష్టి సేవ ట్రస్ట్ గురించి',
    'about.hero.title': 'సంరక్షణ మరియు విద్య ద్వారా',
    'about.hero.titleAccent': 'జీవితాలను మార్చడం',
    'about.hero.description': 'విశ్వశాంతి సృష్టి సేవ ట్రస్ట్ తెలంగాణలో పనిచేస్తున్న ఒక నమోదిత భారతీయ స్వచ్ఛంద సంస్థ (రిజిస్టర్ నెం. 768K IV/2024 / REGD.NO: 2091/2001). 2001 నుండి, అనాథ మరియు నిరుపేద పిల్లలకు సంపూర్ణ సంరక్షణ అందించడం, స్వయం సహాయక బృందాల (SHGs) ద్వారా మహిళలను సాధికారపరచడం మరియు అవగాహన కార్యక్రమాల ద్వారా ఆరోగ్యకరమైన సమాజాలను నిర్మించడానికి మేము కట్టుబడి ఉన్నాము.',
    'about.mission': 'మా ఆశయం',
    'about.mission.desc': 'ప్రతి బిడ్డకు వారి పరిస్థితులతో సంబంధం లేకుండా నాణ్యమైన విద్య, సమతుల్య పోషకాహారం, ఆరోగ్య సంరక్షణ మరియు క్రమశిక్షణ లభించే సురక్షితమైన, పెంపొందించే ఇల్లాన్ని అందించడం. మేము మహిళలను సాధికారపరుస్తాము, HIV/AIDS ప్రభావిత కుటుంబాలకు మద్దతు ఇస్తాము మరియు పర్యావరణ పరిరక్షణను ప్రోత్సహిస్తాము.',
    'about.vision': 'మా లక్ష్యం',
    'about.vision.desc': 'పేదరికం వల్ల ఏ బిడ్డకూ అవకాశం నిరాకరించబడని సమాజం, మరియు మహిళలు, వృద్ధులు మరియు వ్యాధి బారిన పడిన వారు తమ జీవితాలను గౌరవప్రదంగా గడపడానికి అవసరమైన వనరులు, నైపుణ్యాలతో సాధికారత పొందే సమాజం.',
    'about.values.title': 'మా విలువలు',
    'about.journey.title': 'మా ప్రయాణం',
    'about.cta.title': 'మార్పు తీసుకురావడంలో మాతో చేరండి',
    'about.cta.desc': 'మీ మద్దతు జీవితాలను మారుస్తుంది. మీరు విరాళం ఇచ్చినా, స్వచ్ఛందంగా సేవ చేసినా లేదా మా ఆశయాన్ని పంచుకున్నా — ప్రతి చర్య ముఖ్యమైనదే.',
    
    // Volunteer Page
    'volunteer.hero.badge': 'భాగస్వామ్యం అవ్వండి',
    'volunteer.hero.title': 'స్వచ్ఛంద సేవ చేయండి',
    'volunteer.hero.description': 'సహాయం అవసరమైన పిల్లలతో మరియు సమాజంతో మీ సమయాన్ని, నైపుణ్యాలను మరియు సానుభూతిని పంచుకోండి. వారానికి కొన్ని గంటలు కేటాయించగలిగినా లేదా ప్రాజెక్ట్‌ను నడిపించాలనుకున్నా, మీకోసం ఒక స్థానం ఉంది.',
    'volunteer.roles.title': 'స్వచ్ఛంద సేవా పాత్రలు',

    'volunteer.role.teaching.title': 'బోధన & ట్యూటరింగ్',
    'volunteer.role.teaching.desc': 'పిల్లలకు హోమ్‌వర్క్, కంప్యూటర్ నైపుణ్యాలు మరియు ఇంగ్లీష్ భాషా నైపుణ్యంతో సహాయం చేయండి.',
    'volunteer.role.teaching.commitment': 'వారానికి 4-6 గంటలు',
    'volunteer.role.mentorship.title': 'మార్గదర్శకత్వం',
    'volunteer.role.mentorship.desc': 'కౌమారదశలో ఉన్న పిల్లలకు మార్గదర్శకత్వం, కెరీర్ కౌన్సెలింగ్ మరియు మానసిక మద్దతును అందించండి.',
    'volunteer.role.mentorship.commitment': 'వారానికి 2-4 గంటలు',
    'volunteer.role.events.title': 'కార్యక్రమాల సమన్వయం',
    'volunteer.role.events.desc': 'నిధుల సేకరణ, అవగాహన ప్రచారాలు మరియు సామాజిక నిశ్చితార్థ కార్యక్రమాలను నిర్వహించండి.',
    'volunteer.role.events.commitment': 'సౌకర్యవంతమైనది',
    'volunteer.role.medical.title': 'వైద్యం & ఆరోగ్యం',
    'volunteer.role.medical.desc': 'ఆరోగ్య శిబిరాలు, పోషకాహార వర్క్‌షాప్‌లు నిర్వహించండి లేదా వైద్య నైపుణ్యాన్ని అందించండి.',
    'volunteer.role.medical.commitment': 'ప్రాజెక్ట్ ఆధారితం',
    'volunteer.form.title': 'స్వచ్ఛంద సేవకుల నమోదు ఫారమ్',
    'volunteer.form.name': 'పూర్తి పేరు',
    'volunteer.form.email': 'ఈమెయిల్ చిరునామా',
    'volunteer.form.phone': 'ఫోన్',
    'volunteer.form.city': 'నగరం / పట్టణం',
    'volunteer.form.skills': 'నైపుణ్యాలు & ఆసక్తులు',
    'volunteer.form.days': 'అందుబాటులో ఉన్న రోజులు',
    'volunteer.form.hours': 'వారానికి కేటాయించే సమయం (గంటలు)',
    'volunteer.form.consent': 'భారతదేశ DPDP చట్టం 2023 మార్గదర్శకాల ప్రకారం ఈ స్వచ్ఛంద సేవకుల విచారణను నిల్వ చేయడానికి మరియు ప్రాసెస్ చేయడానికి నేను విశ్వశాంతి సృష్టి సేవ ట్రస్ట్‌కు సమ్మతిస్తున్నాను.',
    'volunteer.form.submit': 'నమోదును సమర్పించండి',
    'volunteer.form.submitting': 'నమోదును సమర్పిస్తోంది...',
    'volunteer.form.success.title': 'నమోదు విజయవంతమైంది!',
    'volunteer.form.success.desc': 'మీ నమోదు విజయవంతంగా సమర్పించబడింది! మా స్వచ్ఛంద సమన్వయకర్త త్వరలో మిమ్మల్ని సంప్రదిస్తారు.',
    'volunteer.form.success.button': 'మరొక స్వచ్ఛంద సేవకుడిని నమోదు చేయండి',
    'volunteer.form.validation.name': 'పేరు కనీసం 2 అక్షరాలు ఉండాలి.',
    'volunteer.form.validation.city': 'నగరం కనీసం 2 అక్షరాలు ఉండాలి.',
    'volunteer.form.validation.skills': 'దయచేసి కనీసం ఒక నైపుణ్యం/ఆసక్తి ఉన్న విభాగాన్ని ఎంచుకోండి.',
    'volunteer.form.validation.days': 'దయచేసి అందుబాటులో ఉన్న కనీసం ఒక రోజును ఎంచుకోండి.',
    'volunteer.form.validation.hours': 'వారానికి కనీసం 1 గంట కేటాయించడం అవసరం.',
    'volunteer.form.validation.consent': 'మీరు DPDP మార్గదర్శకాల ప్రకారం డేటా ప్రాసెసింగ్‌కు సమ్మతించాలి.',
    'volunteer.form.validation.phone': 'చెల్లని ఫోన్ నంబర్ ఫార్మాట్ (ఉదా. +919876543210).',
    'volunteer.form.placeholder.name': 'మీ పేరు',
    'volunteer.form.placeholder.city': 'ఉదా. హైదరాబాద్',
    'volunteer.skill.teaching': 'బోధన & ట్యూటరింగ్',
    'volunteer.skill.mentorship': 'మార్గదర్శకత్వం',
    'volunteer.skill.events': 'కార్యక్రమాల సమన్వయం',
    'volunteer.skill.medical': 'వైద్యం & ఆరోగ్య మద్దతు',
    'volunteer.skill.content': 'కంటెంట్ రైటింగ్ & సోషల్ మీడియా',
    'volunteer.skill.it': 'IT & గ్రాఫిక్ డిజైన్',
    'volunteer.skill.admin': 'పరిపాలనా మద్దతు',
    
    // Contact Page
    'contact.hero.badge': 'సంప్రదించండి',
    'contact.hero.title': 'మమ్మల్ని సంప్రదించండి',
    'contact.hero.description': 'మేము మీ నుండి వినడానికి ఇష్టపడతాము. మా కార్యక్రమాల గురించి మీకు ప్రశ్నలు ఉన్నా, విరాళం ఇవ్వాలనుకున్నా, స్వచ్ఛంద సేవ చేయాలనుకున్నా, లేదా పిల్లల ప్రవేశాల గురించి విచారించాలనుకున్నా — మమ్మల్ని సంప్రదించండి, మేము 24 గంటల్లో స్పందిస్తాము.',
    'contact.form.name': 'పూర్తి పేరు',
    'contact.form.email': 'ఈమెయిల్',
    'contact.form.phone': 'ఫోన్',
    'contact.form.subject': 'విషయం',
    'contact.form.message': 'సందేశం',
    'contact.form.consent': 'గోప్యతా విధానంలో వివరించిన విధంగా విశ్వశాంతి సృష్టి సేవ ట్రస్ట్ నా వ్యక్తిగత డేటాను ప్రాసెస్ చేయడానికి నేను సమ్మతిస్తున్నాను.',
    'contact.form.submit': 'సందేశాన్ని పంపండి',
    'contact.sidebar.title': 'నేరుగా మమ్మల్ని చేరుకోండి',

    'contact.sidebar.address': 'ఇంటి నెం. 2-6-410, జైపురి కాలనీ, నాగోల్, ఉప్పల్ మండల్, మేడ్చల్ మల్కాజిగిరి జిల్లా, తెలంగాణ, భారతదేశం',
    'contact.sidebar.hours.title': 'కార్యాలయ వేళలు',
    'contact.sidebar.hours.days': 'సోమవారం - శనివారం: ఉదయం 9:00 - సాయంత్రం 6:00 IST',
    'contact.sidebar.hours.sunday': 'ఆదివారం: సెలవు',
    'contact.sidebar.emergency.title': 'అత్యవసర పరిస్థితి / ప్రవేశాలు',
    'contact.sidebar.emergency.desc': 'అత్యవసర పిల్లల ప్రవేశాల విచారణ కోసం, దయచేసి నేరుగా మమ్మల్ని సంప్రదించండి',
    'contact.form.subject.general': 'సాధారణ విచారణ',
    'contact.form.subject.admission': 'పిల్లల ప్రవేశాల విచారణ',
    'contact.form.subject.partnership': 'భాగస్వామ్యం / CSR',
    'contact.form.subject.media': 'మీడియా & ప్రెస్',
    'contact.form.validation.name': 'పేరు కనీసం 2 అక్షరాలు ఉండాలి.',
    'contact.form.validation.message': 'సందేశం కనీసం 10 అక్షరాలు ఉండాలి.',
    'contact.form.validation.consent': 'మీరు DPDP మార్గదర్శకాల ప్రకారం డేటా ప్రాసెసింగ్‌కు సమ్మతించాలి.',
    'contact.form.validation.phone': 'చెల్లని ఫోన్ నంబర్ ఫార్మాట్ (ఉదా. +919876543210).',
    'contact.form.success': 'మీ సందేశం విజయవంతంగా పంపబడింది. మేము 24 గంటల్లో మిమ్మల్ని సంప్రదిస్తాము!',
    'contact.form.success.title': 'విచారణ పంపబడింది!',
    'contact.form.success.button': 'మరొక విచారణను పంపండి',
    'contact.form.placeholder.name': 'మీ పూర్తి పేరు',
    'contact.form.placeholder.email': 'you@example.com',
    'contact.form.placeholder.phone': '+91 98765 43210',
    'contact.form.placeholder.message': 'మీకు మేము ఎలా సహాయపడగలమో చెప్పండి...',
    'contact.form.sending': 'సందేశాన్ని పంపుతోంది...',

    // Programmes Page
    'programmes.hero.badge': 'మా సేవలు',
    'programmes.hero.title': 'కార్యక్రమాలు',
    'programmes.hero.titleAccent': 'జీవితాలను మారుస్తాయి',
    'programmes.hero.desc': 'నివాస బాలల సంరక్షణ నుండి మహిళా సాధికారత వరకు, మా కార్యక్రమాలు తెలంగాణ వ్యాప్తంగా ఉన్న వెనుకబడిన వర్గాల అత్యంత కీలకమైన అవసరాలను తీరుస్తాయి.',
    'programmes.card.children.title': 'పిల్లల హోమ్',
    'programmes.card.children.desc': '4-12 సంవత్సరాల వయస్సు గల అనాథ మరియు నిరుపేద పిల్లలకు నిర్మాణాత్మక దినచర్యలు, క్రమశిక్షణ మరియు ప్రేమపూర్వక కుటుంబ వాతావరణంతో కూడిన సురక్షితమైన నివాస సంరక్షణ.',
    'programmes.card.children.stats': '120+ పిల్లల సంరక్షణ',
    'programmes.card.education.title': 'విద్యా సహాయం',
    'programmes.card.education.desc': 'వెనుకబడిన పిల్లల కోసం పాఠశాల నమోదు, యూనిఫాంలు, స్టేషనరీ, ట్యూషన్ మరియు కంప్యూటర్ పరిజ్ఞానంతో కూడిన పూర్తి విద్యా సహాయం.',
    'programmes.card.education.stats': '500+ విద్యార్థులకు మద్దతు',
    'programmes.card.women.title': 'మహిళా సాధికారత',
    'programmes.card.women.desc': 'స్వయం సహాయక బృందాలు (SHGs), నైపుణ్య శిక్షణ, మైక్రోఫైనాన్స్ యాక్సెస్ మరియు కమ్యూనిటీ నాయకత్వ అభివృద్ధి ద్వారా మహిళలను సాధికారపరచడం.',
    'programmes.card.women.stats': '15+ active SHGs',
    'programmes.card.hiv.title': 'HIV/AIDS అవగాహన',
    'programmes.card.hiv.desc': 'కమ్యూనిటీ స్థాయిలో అవగాహన కార్యక్రమాలు, పరీక్షల సౌకర్యం, అపవాదు తొలగింపు ప్రచారాలు మరియు ప్రభావిత వ్యక్తులు & కుటుంబాలకు మద్దతు.',
    'programmes.card.hiv.stats': '5,000+ మందికి చేరింది',
    'programmes.card.environment.title': 'పర్యావరణం',
    'programmes.card.environment.desc': 'స్థానిక సమాజాలలో పర్యావరణ స్థిరత్వాన్ని ప్రోత్సహించే మొక్కల పెంపకం, పారిశుద్ధ్య ప్రచారాలు మరియు అవగాహన కార్యక్రమాలు.',
    'programmes.card.environment.stats': 'కొనసాగుతున్న కార్యక్రమాలు',
    'programmes.card.aged.title': 'వృద్ధుల సంరక్షణ',
    'programmes.card.aged.desc': 'కుటుంబ మద్దతు లేని వృద్ధ పురుషులు మరియు మహిళల కోసం ప్రణాళికాబద్ధమైన నివాస గృహాలు, గౌరవం, వైద్య సంరక్షణ మరియు సహచర్యాన్ని నిర్ధారిస్తాయి.',
    'programmes.card.aged.stats': 'త్వరలో రాబోతోంది',
    
    // Days
    'day.mon': 'సోమ',
    'day.tue': 'మంగళ',
    'day.wed': 'బుధ',
    'day.thu': 'గురు',
    'day.fri': 'శుక్ర',
    'day.sat': 'శని',
    'day.sun': 'ఆది',

    // Countries
    'country.IN': 'భారతదేశం',
    'country.US': 'అమెరికా (యుఎస్)',
    'country.GB': 'యునైటెడ్ కింగ్‌డమ్',
    'country.CA': 'కెనడా',
    'country.AU': 'ఆస్ట్రేలియా',
    'country.SG': 'సింగపూర్',
    'country.DE': 'జర్మనీ',
    'country.FR': 'ఫ్రాన్స్',
    'country.AE': 'యునైటెడ్ అరబ్ ఎమిరేట్స్',

    // Donate Page FAQs & Pricing Frequencies
    'donate.frequency.once.abbr': 'సారి',
    'donate.frequency.monthly.abbr': 'నెల',
    'donate.frequency.yearly.abbr': 'సంవత్సరం',
    'donate.trust.exempt': 'పన్ను మినహాయింపు ధృవీకరించబడింది',
    'donate.trust.secure': '256-బిట్ సురక్షితం',
    'donate.trust.funds': 'కార్యక్రమాలకు నిధులు',
    'donate.faq.title': 'విరాళాల గురించి తరచుగా అడిగే ప్రశ్నలు',
    'donate.faq.more': 'మరిన్ని ప్రశ్నలు ఉన్నాయా? మమ్మల్ని సంప్రదించండి లేదా +91 80745 89091 కి కాల్ చేయండి',
    'donate.faq.or': 'లేదా',
    'donate.faq.contactUs': 'మమ్మల్ని సంప్రదించండి',
    'donate.faq.q1': 'నా విరాళానికి పన్ను మినహాయింపు ఉందా?',
    'donate.faq.a1': 'అవును. విశ్వశాంతి సృష్టి సేవ ట్రస్ట్ ఆదాయపు పన్ను చట్టం సెక్షన్ 80G కింద నమోదైంది. ప్రతి విరాళానికి మీకు సరైన 80G రసీదు లభిస్తుంది, దీనిని పన్ను మినహాయింపుల కోసం ఉపయోగించవచ్చు.',
    'donate.faq.q2': 'నేను భారతదేశం వెలుపల నుండి విరాళం ఇవ్వవచ్చా?',
    'donate.faq.a2': 'అవును. మేము FCRA నమోదిత సంస్థ మరియు విదేశీ కరెన్సీలో విరాళాలను స్వీకరించగలము. విదేశీ విరాళాలు భారతీయ చట్టాలకు అనుగుణంగా మా ప్రత్యేక FCRA బ్యాంక్ ఖాతా ద్వారా ప్రాసెస్ చేయబడతాయి.',
    'donate.faq.q3': 'నా డబ్బు ఎలా ఉపయోగించబడుతుంది?',
    'donate.faq.a3': 'మీ విరాళంలో 100% నేరుగా కార్యక్రమ ఖర్చులకు — పిల్లల ఆశ్రయం, ఆహారం, విద్య మరియు ఆరోగ్య సంరక్షణకు వెళుతుంది. పరిపాలనా ఖర్చులు సంస్థాగత గ్రాంట్ల ద్వారా విడిగా నిధులు సమకూరుతాయి.',
    'donate.faq.q4': 'నేను స్పాన్సర్ చేసే బిడ్డ గురించిన అప్‌డేట్స్ నాకు అందుతాయా?',
    'donate.faq.a4': 'నెలవారీ స్పాన్సర్‌లు విద్యా ప్రతిభ మరియు శ్రేయస్సు నివేదికలతో సహా త్రైమాసిక పురోగతి నివేదికలను అందుకుంటారు. మేము పిల్లల గోప్యతను గౌరవిస్తాము మరియు భాగస్వామ్యం చేయబడిన ఫోటోగ్రాఫ్‌ల కోసం కఠినమైన సమ్మతి మార్గదర్శకాలను అనుసరిస్తాము.',
    'donate.faq.q5': 'నేను నా పునరావృత విరాళాన్ని రద్దు చేయవచ్చా?',
    'donate.faq.a5': 'అవును, మీరు మీ దాత డాష్‌బోర్డ్ ద్వారా లేదా నేరుగా మమ్మల్ని +91 80745 89091 లో సంప్రదించడం ద్వారా ఎప్పుడైనా మీ పునరావృత విరాళాన్ని రద్దు చేయవచ్చు లేదా సవరించవచ్చు.',
    'programmes.card.learnMore': 'మరింత తెలుసుకోండి',
  }
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>('en');

  // Load language preference from localStorage if available
  useEffect(() => {
    const savedLang = localStorage.getItem('language') as Language;
    if (savedLang === 'en' || savedLang === 'te') {
      setLanguageState(savedLang);
      document.documentElement.lang = savedLang;
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('language', lang);
    document.documentElement.lang = lang;
  };

  const t = (key: string): string => {
    return translations[language][key] || translations['en'][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
